language: node_js
node_js:
  - 9
  - 10
  - 11
  - 12
  - 13
cache:
  directories:
    - node_modules
install:
- npm install
script:
- npm run lint
- npm run test:coverage
after_script:
- npm run coveralls
