# Test against this version of Node.js
environment:

  matrix:
  # node.js
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

  CODIGO_COMERCIO:
    secure: HPzNNsgJ6ZM3Q2mh0tiGeA==
  LLAVE_COMERCIO:
    secure: jQxgKYOeHP2GNI6szpCbLAwj3baO10LWUG4WQWfMwqoUk2vnFtoqv+3nHsMYCqm2
  ENV:
    secure: h36A2B9psYVxrgWG5x0IxQ==
  SNYK_TOKEN:
    secure: dNww2ZmbSlumEu7CY8K00hunQsIOutZzW/2HLxYMH8UX+H9fxJA0ZI5O6fG+OFHL

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test


# Don't actually build.
build: off

# Run snyk auth
before_build:
  - snyk auth $SNYK_TOKEN