version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm ci
      - run:
          name: Run lint
          command: |
            npm run lint
      - run:
          name: Run unit & integration tests
          command: |
            npm run test:coverage
      - run:
          name: Upload to coveralls
          command: |
            npm run coveralls


workflows:
  execute_tests:
    jobs:
      - run_tests:
          filters:
            branches:
              only:
                - master
                - dev
